apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config
  namespace: {{ .Values.namespace }}

data:
  SERVER_PORT: "8005"
  DB_HOST: "chatdb.cb4ywoiqgmmt.ap-south-1.rds.amazonaws.com"
  DB_NAME: "chatdb"