apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.auth.replicas }}

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service

          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"

          imagePullPolicy: Always

          ports:
            - containerPort: 8005

          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SERVER_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_NAME

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          startupProbe:
            tcpSocket:
              port: 8005
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 8005
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8005
            initialDelaySeconds: 60
            periodSeconds: 20