apiVersion: v1
kind: Secret

metadata:
  name: auth-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USERNAME: admin
  DB_PASSWORD: ChangeMe123!
  JWT_SECRET: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007