server.port=8010

spring.data.mongodb.uri=${MONGO_URI}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true