apiVersion: v1
kind: ConfigMap

metadata:
  name: chat-config
  namespace: chat-dev

data:
  SERVER_PORT: "8010"

  MONGO_URI: mongodb://admin:password@mongodb:27017/spring_chat_app?authSource=admin
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"